(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.title = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Isolation Mode
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAKA4QgCgFAAgJIAAgRQAAgPgLAAIgGAAIAAAuIgSAAIAAhvIAbAAQAZAAAAAaIAAAJQAAARgLAEQALAFAAATIAAARQAAAJADAFgAgJgFIAHAAQAJAAAAgMIAAgKQAAgMgIAAIgIAAg");
	this.shape.setTransform(25.2,11.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgaAdIAAg5QAAgcAaAAQAbAAAAAcIAAA5QAAAcgbAAQgaAAAAgcgAgIgdIAAA7QAAALAIAAQAJAAAAgLIAAg7QAAgLgJAAQgIAAAAALg");
	this.shape_1.setTransform(18.7,11.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgIA4IAAhfIgSAAIAAgQIA1AAIAAAQIgSAAIAABfg");
	this.shape_2.setTransform(12.6,11.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgZAdIAAg5QAAgcAZAAQAaAAAAAcIAAALIgRAAIAAgMQAAgLgJAAQgIAAAAALIAAA7QAAALAIAAQAJAAAAgLIAAgQIARAAIAAAPQAAAcgaAAQgZAAAAgcg");
	this.shape_3.setTransform(6.5,11.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgXA4IAAhvIAvAAIAAAQIgdAAIAAAfIAXAAIAAAPIgXAAIAAAhIAdAAIAAAQg");
	this.shape_4.setTransform(0.6,11.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAKA4IgVhRIAABRIgQAAIAAhvIAWAAIARBCIAAhCIAQAAIAABvg");
	this.shape_5.setTransform(-5.8,11.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAKA4IgVhRIAABRIgQAAIAAhvIAWAAIARBCIAAhCIAQAAIAABvg");
	this.shape_6.setTransform(-12.5,11.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgaAdIAAg5QAAgcAaAAQAbAAAAAcIAAA5QAAAcgbAAQgaAAAAgcgAgIgdIAAA7QAAALAIAAQAJAAAAgLIAAg7QAAgLgJAAQgIAAAAALg");
	this.shape_7.setTransform(-19.1,11.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgZAdIAAg5QAAgcAZAAQAaAAAAAcIAAALIgRAAIAAgMQAAgLgJAAQgIAAAAALIAAA7QAAALAIAAQAJAAAAgLIAAgQIARAAIAAAPQAAAcgaAAQgZAAAAgcg");
	this.shape_8.setTransform(-25.3,11.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgXA4IAAhvIASAAIAABfIAcAAIAAAQg");
	this.shape_9.setTransform(14.3,-2.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AANA4IgDgVIgUAAIgEAVIgQAAIAShvIAZAAIASBvgAgIAVIAQAAIgIg5g");
	this.shape_10.setTransform(8,-2.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgIA4IAAhvIARAAIAABvg");
	this.shape_11.setTransform(3.1,-2.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgZAdIAAg5QAAgcAZAAQAaAAAAAcIAAALIgQAAIAAgMQAAgLgJAAQgIAAAAALIAAA7QAAALAIAAQAJAAAAgLIAAgQIAQAAIAAAPQAAAcgaAAQgZAAAAgcg");
	this.shape_12.setTransform(-1.4,-2.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgaAdIAAg5QAAgcAaAAQAbAAAAAcIAAA5QAAAcgbAAQgaAAAAgcgAgIgdIAAA7QAAALAIAAQAJAAAAgLIAAg7QAAgLgJAAQgIAAAAALg");
	this.shape_13.setTransform(-7.7,-2.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgZAdIAAgHIAQAAIAAAIQAAALAJAAQAJAAAAgLQAAgKgQgQQgSgPAAgRQAAgcAZAAQAaAAAAAcIAAADIgRAAIAAgEQAAgLgIAAQgIAAAAALQAAAKAQAQQARAPAAARQAAAcgaAAQgZAAAAgcg");
	this.shape_14.setTransform(-13.9,-2.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgLAgIAAg/IAXAAIAAAHIgQAAIAAAVIAOAAIAAAGIgOAAIAAAWIAQAAIAAAHg");
	this.shape_15.setTransform(3.8,-14);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAHAgIAAgdIgNAAIAAAdIgIAAIAAg/IAIAAIAAAcIANAAIAAgcIAIAAIAAA/g");
	this.shape_16.setTransform(-0.1,-14);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgDAgIAAg4IgKAAIAAgHIAbAAIAAAHIgKAAIAAA4g");
	this.shape_17.setTransform(-3.9,-14);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-27.9,-17.2,55.9,34.6);


(lib.lbranch = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Isolation Mode
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F3F8EC").s().p("AgcAWQATgYAXgVIAPAPIgYAWQgEAEgEADIgDABQgFACgHAAQgGAAgEgCg");
	this.shape.setTransform(-21.3,13.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F3F8EC").s().p("AgJAiQgEgFgDgHQgCgFAAgHIACgKIAQghIATAJIgPAeIgBADIgGATQgBAEgEACg");
	this.shape_1.setTransform(-26.3,22.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F3F8EC").s().p("AgbAGQADgFAEgEQAFgEAFgCIAggPIAIAVQgeAKgdARQgBgJADgJg");
	this.shape_2.setTransform(-11.7,7.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#DDEBC7").s().p("AgfAUQAIgPAOgSQAEACAFAAQAHAAAFgCIAEgCQAFgCAEgEIAHgHQgaAagRAfg");
	this.shape_3.setTransform(-23.2,16.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#DDEBC7").s().p("AhVgBIARgFIAiAJIAAgBIAMADQADABADgCQAFgDABgEQABgFgDgDQgCgEgFgBQAygFAuAKQALACgCAKQgBAEgEADQgEACgEgBQhMgPhKAYg");
	this.shape_4.setTransform(-0.9,4.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#DDEBC7").s().p("AAAARQgDgBgDgEQgCgFACgEIAGgUIAAALQAAAGAAAEQADAHAFAFIgFACIgDgBg");
	this.shape_5.setTransform(-28.1,24);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#DDEBC7").s().p("AgTAZIgPgPQAggcAlgSQgFADgFAEQgEAEgCAGQgEAJACAJQgZAQgXAWg");
	this.shape_6.setTransform(-16.4,9.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#DDEBC7").s().p("AgWAZQgKgKAAgOQAAgNAKgKQAJgKAOAAQAGAAAGACQAHADAEAFIAJAJIgQAOIgIgHIgEgDIgEgBIgFABIgDACQgDAFAAADQAAAFADADQADAEAFAAIAEgBIAEgCIAGgGQgNAOgLAPQgJgDgEgFg");
	this.shape_7.setTransform(-23.2,12.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#DDEBC7").s().p("AgSAfQgFgCgFgFIAAAAQAEgCACgFIAHgRIgBAAIABAEQACAFAEACQAEACAFgBQAEgCACgEQACgFgBgDIgDgEIgEgDIgJgFIAJgUIAKAFQAGADAFAGIAGAKQAFANgGAMQgFAKgKAGIgEABQgGADgFAAQgHAAgHgEg");
	this.shape_8.setTransform(-24.4,23.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#DDEBC7").s().p("AgMAaQgNgFgGgNIgCgIQAPgIAOgHIAAAAIgEADIgCADQgCAFACAEQABAEAFACQAEABAEgBQAFgCACgEIABgEIgBgFIgFgLIgKAFQAPgHAPgGIAFALQADAIgBAGQAAAFgCAGQgFALgLAGIgCABQgHADgGAAQgGAAgGgDg");
	this.shape_9.setTransform(-11.3,9.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F3F8EC").s().p("AAHAHIgagHQATgFAUgDIgGARg");
	this.shape_10.setTransform(-5.8,4.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F3F8EC").s().p("AAAALIgLgDIAFgQIAJgCIAAAAQAFABACAEQADADgBAEQgBAFgFADIgEABIgCAAg");
	this.shape_11.setTransform(-3.2,4.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F3F8EC").s().p("AgPABQgDgCAAgFQgBgEAEgEQACgEAFAAQAEAAADADIAUARIgOARg");
	this.shape_12.setTransform(-17.3,-2.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F3F8EC").s().p("AgPAOIgDgDQgFgDgDgGQgFgIABgKIAbAMIADACIAHACQAJACAQAEIgBAEQgUACgSAFg");
	this.shape_13.setTransform(-7,2.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F3F8EC").s().p("AgfgOQAFgDAFgBQAEgCAHABQAHABAGADIAdARIgLASQgXgMgdgWg");
	this.shape_14.setTransform(-13.5,0.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#DDEBC7").s().p("AgNAGIALgRIgMgIIAOAJQAAAKAEAIQADAGAFADIADADIgcgOg");
	this.shape_15.setTransform(-10.1,1.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#DDEBC7").s().p("AANAFQgHgDgGgBQgGgBgFACQgFABgFADIAAAAIAOgQQASAOALAHg");
	this.shape_16.setTransform(-14.6,-1.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#DDEBC7").s().p("AgDgBIAIABIgJACg");
	this.shape_17.setTransform(-3.4,3.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#DDEBC7").s().p("AgVAaQgGgGgDgGQgDgFAAgGQgBgNAJgLQAJgLAOgBQANgBALAJQAKAJABAOQABAFgCAGQgBAGgFAGIgIAKIgRgOIAIgJIACgFIABgDQgBgFgEgDQgDgEgEABIgFABQgHAFABAGIABAEIADAEIAFAEQgEgCgEAAQgEAAgDADQgDAEAAAEQAAAFAEADIAFAEg");
	this.shape_18.setTransform(-17.2,-5.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#ADD278").s().p("AgDgBIAHADIAAAAIgHgDg");
	this.shape_19.setTransform(-8.1,4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#DDEBC7").s().p("AAIAWIAEgMIAAgFIgBgEQgCgDgGgCQgDgBgEACIgBAAQgEADgBAEQgCAEADAFIADADIgbgMIACgGQAEgNAMgHQAMgHAMAEQAOAEAHAMIAEALQAAAGgBAIIgEALIgVgFg");
	this.shape_20.setTransform(-6.7,0.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#DDEBC7").s().p("AgRAaQgMgHgDgNQgEgMAHgNQAFgIAHgDQAcAWAYAMIgGAKQgFAHgFAEIgLAFIgIABQgJAAgIgFgAgCgNQgFAAgDAFQgCAEABAEQABAFAEACQAFADADgBIAEgCIAEgEIAGgJIgKgGIgFgCg");
	this.shape_21.setTransform(-14.9,2.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-28.8,-9.2,36.6,35.9);


(lib.keywords = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Art
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#8EC549").s().p("AAEAjIgMgzIgPApIgJgCIAUg8IAJACIANAzIAOgpIAJADIgUA8g");
	this.shape.setTransform(26.8,-62.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#8EC549").s().p("AgHAgQgJgCgGgJQgCgFAAgGIACgOQAEgMACgDQACgGAGgDQAIgFAIADQAKACAEAIQAEAFAAAGIgEAPQgDALgBAEQgDAFgFADQgGADgFAAIgGAAgAgEgVQgFAEgDAPQgEAPADAEQACAFAGABQAFACAEgDQAGgDADgQQAEgOgDgFQgDgFgFgBIgDgBQgDAAgEACg");
	this.shape_1.setTransform(20.7,-64);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#8EC549").s().p("AgKAfIALg+IAKACIgLA9g");
	this.shape_2.setTransform(16.4,-65);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#8EC549").s().p("AgMAgIAIg1IgSgDIABgJIAsAHIgBAIIgSgCIgHA2g");
	this.shape_3.setTransform(12.7,-65.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#8EC549").s().p("AgBAgQgLgBgFgGQgEgFgBgGIAAgPIACgPQACgGAEgEQAHgGAJAAQATACADAUIgKgBQgCgLgKgBQgFAAgEADQgEAEgBAQQgBAOADAFQADAEAGABQAKABADgLIAKAAQgFATgRAAIgBgBg");
	this.shape_4.setTransform(6.7,-66.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#8EC549").s().p("AgUAgIABg/IAoAAIAAAIIgfAAIAAATIAaABIAAAHIgaAAIAAATIAeAAIAAAJg");
	this.shape_5.setTransform(1.1,-66.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#8EC549").s().p("AgagdIAJgBIAhAqIgEgsIAKAAIAEA+IgJABIgggqIAEAsIgKABg");
	this.shape_6.setTransform(-5.1,-66.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#8EC549").s().p("AgcgbIAJgBIAjAnIgHgsIAKgBIAKA+IgJABIgjgnIAHAsIgKABg");
	this.shape_7.setTransform(-11.8,-65.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#8EC549").s().p("AgJAdQgFgDgDgGQgCgEgCgKIgDgPQAAgGADgFQAFgIAKgDQAJgCAHAFQAGADACAGIAFAOQACALAAAEQAAAHgDAEQgEAIgKACIgHACQgFAAgFgEgAgEgXQgGACgDAEQgCAFADAPQAEAQAEACQAEAEAGgBQAFgCADgFQADgFgEgOQgDgPgFgDQgDgDgEAAIgCAAg");
	this.shape_8.setTransform(-18.1,-64.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#8EC549").s().p("AgHAeQgGgDgDgFIgFgPQgEgKAAgEQgBgGADgGQAEgHAKgEQASgGAJASIgKADQgGgKgIADQgGACgCAFQgDAFAFAOQAFAPAFADQADACAGgBQAKgDgBgMIAJgDQADAUgSAGIgIACQgEAAgFgDg");
	this.shape_9.setTransform(-23.8,-62.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#8EC549").s().p("AgggVIAIgBIACARIA3gEIAAAJIg2AEIACASIgJABg");
	this.shape_10.setTransform(-80.7,23.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#8EC549").s().p("AgcAVIAmgkIgrAHIgCgJIA+gLIACAIIgnAkIAsgHIABAKIg+AKg");
	this.shape_11.setTransform(-79.8,29);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#8EC549").s().p("AgjgLIAIgCIAIAdIASgFIgGgYIAHgCIAHAYIASgEIgHgeIAIgCIAKAnIg9AQg");
	this.shape_12.setTransform(-78.6,34.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#8EC549").s().p("AgXAcIAegeIgqgFIgEgJIA8gUIADAJIgnAOIAhAEIADAHIgZAXIApgOIADAJIg9AVg");
	this.shape_13.setTransform(-76.7,41.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#8EC549").s().p("AgUAQIAUgXIgegBIgEgKIApADIAZgKIADAJIgYAKIgaAgg");
	this.shape_14.setTransform(-74.8,48.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#8EC549").s().p("AgPAbQgIgDgFgJQgFgKADgHQACgGAFgEIANgIIAOgGQAGgCAGACQAJAEAEAIQAFAJgDAIQgCAGgFADQgEADgKAFQgKAGgDABIgGABIgGgBgAgFgLQgOAIgCADQgCAGADAFQACAEAFACQAGACANgHQAOgIACgEQACgFgDgFQgCgFgGgCIgCAAQgFAAgLAGg");
	this.shape_15.setTransform(-72.1,52.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#8EC549").s().p("AgiAJIAlgWQAIgFAIADQAIACAFAIQAEAIgCAIIgJgDQACgEgDgFQgGgJgLAGIgkAVg");
	this.shape_16.setTransform(-69.5,56.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#8EC549").s().p("AgRAfIATgxIgkAZIgFgHIAzglIAGAHIgUAxIAkgYIAGAHIg0Akg");
	this.shape_17.setTransform(-66.3,62.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#8EC549").s().p("AglAFIAHgFIAUAXIANgMIgQgUIAHgFIAQAUIAPgMIgUgXIAHgGIAaAgIgxAng");
	this.shape_18.setTransform(-62.7,66.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#8EC549").s().p("AgnAAIAFgHIA1AFIgigcIAGgIIAxAnIgFAHIg1gFIAiAcIgGAIg");
	this.shape_19.setTransform(64.3,66.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#8EC549").s().p("AAAAbIgMgIIgNgKQgEgEgBgFQgCgJAGgIQAGgJAJgBQAGgCAFADIANAIIANAKQADAEACAFQABAJgFAIQgFAJgKABIgEABQgEAAgEgCgAgKgSQgFAAgEAFQgDAFABAGQABAEANAJQAMAJAGgBQAFAAADgFQAEgFgBgGQgBgEgNgJQgMgIgFAAIgBAAg");
	this.shape_20.setTransform(68.1,61.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#8EC549").s().p("AgdgMIAFgIIA2AgIgFAJg");
	this.shape_21.setTransform(70.5,57.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#8EC549").s().p("AAFAXIAJgPIgwgaIAFgIIAwAaIAIgPIAIAEIgWAmg");
	this.shape_22.setTransform(73,55);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#8EC549").s().p("AgVANQgJgEgDgIQgDgIAEgJQAEgJAJgDQAIgEAJAEIAlASIgEAJIglgSQgNgFgFAMQgGAMANAFIAmARIgEAJg");
	this.shape_23.setTransform(75.5,49.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#8EC549").s().p("AAEAcQgJgDAAgJQgHAHgLgDQgIgDgCgHQgDgHADgHIAJgYIA7AWIgIAWQgDAJgGADQgEABgDAAIgHgBgAABAGQgCAKAIADQAIADAEgKIAFgMIgSgGgAgYgCQgEAJAJAEQAJADAEgKIAFgNIgSgHg");
	this.shape_24.setTransform(77.7,43);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#8EC549").s().p("AgfgEIADgJIA8ARIgDAKg");
	this.shape_25.setTransform(78.9,39);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#8EC549").s().p("AAIAbQgMgDAAgOIggAIIADgLIAegHIADgLIgbgGIADgJIA9APIgGAXQgCAJgGAEQgFACgFAAIgFAAgAADAEQgCALAJACQAKADADgLIADgNIgTgFg");
	this.shape_26.setTransform(80,34.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#8EC549").s().p("AASAWIADgSIg2gIIACgKIA1AKIADgSIAJACIgIArg");
	this.shape_27.setTransform(81.4,29.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#8EC549").s().p("AghAVIABgJIAugYIgrgEIAAgKIA/AGIgBAJIguAYIAsAEIgBAKg");
	this.shape_28.setTransform(82.1,23.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#8EC549").s().p("AgPAWQgGgBgEgFQgHgHABgJQAAgJAGgHQAFgEAGgBIAPgBIAPABQAGABAFAFQAGAHAAAJQAAAJgHAHQgEAEgGACIgQAAIgPgBgAgTgJQgEADAAAGQAAAFAEAEQAEAEAPAAQAQABAEgEQAEgDAAgHQAAgEgEgEQgEgEgQAAIgCAAQgNAAgEADg");
	this.shape_29.setTransform(82.4,16.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#8EC549").s().p("AggABQAAgJAGgGQAEgEAGgCQAFgCALAAQAKgBAEABQAGABAFAEQAHAHABAJQABATgUAEIAAgKQALgCgBgLQAAgFgFgEQgEgDgPABQgQABgDADQgEAFAAAEQAAALAMACIAAAKQgTgDgCgUg");
	this.shape_30.setTransform(82.3,10.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-84,-69.6,169.8,140.2);


(lib.horn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Isolation Mode
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F3F8EC").s().p("AgMALIgHgMIAdgSIAIAOQADAGgBAHQgCAHgHAEQgDABgFAAQgJABgGgKg");
	this.shape.setTransform(-2,-27.1,2.687,2.634,0,0,0,-0.1,-0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F3F8EC").s().p("AAAAWQgGAAgFgFQgFgFAAgHIgBgIIATgNQAJgEAGgBIABAYQAAAIgFAFQgFAFgHABg");
	this.shape_1.setTransform(30.1,-46.5,2.687,2.634,0,0,0,-0.1,-0.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#DDEBC7").s().p("AhcBNIgSgcQgIgNAEgOQADgPANgHIAHAMQAGAJAKAAQAFAAADgCQAHgEACgGQABgHgDgGIgIgPIBbg5IAAAJQABAHAFAFQAFAFAHAAIABAAQAHgBAFgFQAFgFgBgIIgBgZQAYgCAMATIARAcQAIANgDAPQgEAPgMAHIiNBYQgJAGgKAAQgVAAgKgSgAhPAdQgBAAAAAAQAAAAAAAAQgBABABAAQAAAAAAABIASAcQAAAAAAAAQABABAAAAQAAAAAAAAQABAAAAgBICMhXQABAAAAAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIgSgcIgBgBIgBAAg");
	this.shape_2.setTransform(19.1,-27.3,2.687,2.634,0,0,0,-0.1,-0.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F3F8EC").s().p("AABAlQgGAAgFgEQgFgFAAgHIgBgDIgCgkQAAgHAFgFQAFgFAHgBQAGAAAFAFQAGAFAAAHIABAOIACAYQAAAHgFAGQgFAFgHAAg");
	this.shape_3.setTransform(-46.2,-116.9,2.687,2.634,0,0,0,-0.1,-0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#DDEBC7").s().p("AhUhwIgFgKQgDgJgCgbQAAAHAFAEQAFAFAHAAIABAAQAHgBAFgFQAFgEAAgHIADAXIAEAKQALAZCIDyIgeATQiFjsgQgkg");
	this.shape_4.setTransform(-25,-69.7,2.687,2.634,0,0,0,-0.1,-0.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F3F8EC").s().p("AgKAeQgGgFAAgHIgBgGQgBgbAUgNQAFgEAHgBIAEAvIAAABQAAAHgEAGQgFAGgHAAIgCAAQgFAAgFgEg");
	this.shape_5.setTransform(-28.6,-126.3,2.687,2.634,0,0,0,-0.1,-0.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#DDEBC7").s().p("AgxASIgBgTQgBgiABgMQACgTAKgMQAKgNAQgEQASgEAOAKQANAKAGAVQAEANADAbIAFBCQgHACgFADQgUAOABAbIgJhtQgEgogHgFQAAgBgBAAQAAAAgBAAQAAAAgBAAQgBAAgBAAQgIACgCAPQAAANAAAcIABAUIADBNQgBgFgFgEQgFgFgIAAQgHABgFAFQgEAFAAAGIgDhPg");
	this.shape_6.setTransform(-38.6,-148,2.687,2.634,0,0,0,-0.1,-0.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F3F8EC").s().p("AAAAYIgWgWQgFgEgBgHQAAgHAFgGQAFgFAHAAQAHgBAEAFIAXAWQAFADABAHQAAAIgFAFQgFAFgHABIgBAAQgGAAgFgEg");
	this.shape_7.setTransform(1.8,-104.1,2.687,2.634,0,0,0,-0.1,-0.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#DDEBC7").s().p("AAYA4QgBgUgKgYQgRgxgpgZIgCgCIgNgMQAGAFAGgBQAHAAAFgFQAFgGAAgHQgBgHgFgFIgMgLIAZAWQAwAhAWA6QAMAdABAYIACArQgGABgJAFIgUAMg");
	this.shape_8.setTransform(18.2,-77.6,2.687,2.634,0,0,0,-0.1,-0.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#DDEBC7").s().p("AAZBGIhOh/QgEgJAAgLIABAGQAAAHAGAFQAGAFAHgBQAHAAAFgGQAEgGAAgHIAAgBIAAAEIBMB6QAEAGgCAHQgBAIgGADQgFADgFAAQgJAAgGgIg");
	this.shape_9.setTransform(-17.8,-102.6,2.687,2.634,0,0,0,-0.1,-0.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#DDEBC7").s().p("AARAzQgFgFgegyIgJgPQgJgIgGAEQgEACABAHIgEgsQAPgEAPAHQAMAGAHAJIABABIAJAQIAjA1IAFAGQgFgFgIABQgGAAgFAFQgGAGABAHQAAAGAEAEg");
	this.shape_10.setTransform(-11.5,-119.9,2.687,2.634,0,0,0,-0.1,-0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-173.1,102.8,171.4);


(lib.heart = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_65 = function() {
		//this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(65).call(this.frame_65).wait(25));

	// Isolation Mode
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F3F8EC").s().p("AgIAXQgEgCgCgFQgFgIAFgIIAOgYIAPAYQAFAIgFAIIAAABQgFAIgKAAQgFAAgDgCg");
	this.shape.setTransform(0.6,14.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#DDEBC7").s().p("Ah5DtQAFgIgFgJIgPgYQAjg3ApgnIA8g1QAZgUAVgTQA5gzgBgxQABgughghQghghgtAAQgrAAggAdQggAcgEArIAAgDQgDgfgOgZQATgiAhgVQAjgVApAAQA8AAAqArQAsArgBA9QABBChEA8IgwAoQgpAkgQAPQgyAvgkBAg");
	this.shape_1.setTransform(14.3,-8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F3F8EC").s().p("AgJAiIgBAAIgCgDIgBgBIgCgCIAAgBIgBgFIgBAAIAAgEQAEgdANgZQAPAZADAdIAAAEIgBADIgCAEIgBACIgBABQgEAFgJAAQgFAAgEgDg");
	this.shape_2.setTransform(0.6,-20.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#DDEBC7").s().p("AAkB/QgXgWgigdIgvgoQgegbgPgXQgYglAAgnQABg8ArgsQAqgrA8AAQApAAAjAVQAhAVAUAiQgOAZgEAfIAAADQgFgrgfgcQgggdgrAAQgtAAghAhQggAhAAAuQgBAxA5AzIAtAnQAwAoAMANQAsApAiA1IgPAYQgFAJAFAIIAAABQglg/gygwg");
	this.shape_3.setTransform(-13.2,-8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(90));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-26.9,-31.8,55,48.4);


(lib.Path_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,1).p("AAWAAQAAAJgHAHQgGAGgJAAQgIAAgGgGQgHgHAAgJQAAgIAHgGQAGgHAIAAQAJAAAGAHQAHAGAAAIg");
	this.shape.setTransform(3,2.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_1, new cjs.Rectangle(-0.2,-0.2,6.4,6.4), null);


(lib.Path = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,1).p("AAWAAQAAAJgHAHQgGAGgJAAQgIAAgGgGQgHgHAAgJQAAgIAHgGQAGgHAIAAQAJAAAGAHQAHAGAAAIg");
	this.shape.setTransform(3,2.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path, new cjs.Rectangle(-0.2,-0.2,6.4,6.4), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Am5GtIAAvJISvAAIAAPJg");
	mask.setTransform(75.8,-54.1);

	// Layer_10
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgQM6QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQACADAAAEQAAAEgCADQgDADgEAAQgEAAgDgDgAAhM5QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAhCM4QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgABTM2QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAh0MzQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgACGMuQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAinMrQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAC3MkQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAjYMfQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgADmMYQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAkIMRQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAEXMHQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAk2L/QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAFHLzQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAllLrQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAF0LeQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAmRLVQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAGgLFQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAm9K7QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAHKKqQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAnnKeQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAHxKNQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAoPKAQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAIYJtQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAo0JfQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAI9JJQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgApYI7QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAJfIlQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAp5IWQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAKAH+QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAqYHvQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAKdHWQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAq1HGQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAK4GsQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgArPGbQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgALRGAQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgArnFuQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgALnFTQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAr7FAQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAL5ElQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsOEPQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMJD2QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsdDfQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMWDGQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAspCtQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMgCWQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsxB8QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMnBlQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAs3BKQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMrAzQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAs5AYQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMsABQgDgCAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDACQgDADgEAAQgEAAgDgDgAs4gZQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMrgwQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAs1hMQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMmhhQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsuh+QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMeiTQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAslivQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMTjEQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsYjgQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMFjzQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsJkPQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAL0khQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAr1lAQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgALhlQQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgArglsQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgALLl8QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgArImYQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAKymnQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAqunDQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAKXnRQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAqQnrQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAJ5n5QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgApwoSQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAJYoeQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgApOo2QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAI8o7QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAorpYQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAIYpdQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAoEp5QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAHyp9QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAndqXQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAHKqbQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAmzqzQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAGgq2QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAmHrMQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAF1rPQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAlbriQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAFJrkQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAkrr1QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAEar3QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAj+sFQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgADrsHQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAjPsTQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAC7sVQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAieseQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgACMseQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAhtslQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgABasmQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAg7sqQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAAosqQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAgKsrQgDgDAAgEQAAgEADgDQADgDAEAAQADAAADADQADADAAAEQAAAEgDADQgDADgDAAQgEAAgDgDg");
	this.shape.setTransform(0,1);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("ArkHcIAAvJISvAAIAAPJg");
	mask_1.setTransform(-74.1,-49.4);

	// Layer_8
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgQM6QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQACADAAAEQAAAEgCADQgDADgEAAQgEAAgDgDgAAhM5QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAhCM4QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgABTM2QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAh0MzQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgACGMuQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAinMrQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAC3MkQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAjYMfQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgADmMYQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAkIMRQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAEXMHQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAk2L/QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAFHLzQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAllLrQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAF0LeQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAmRLVQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAGgLFQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAm9K7QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAHKKqQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAnnKeQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAHxKNQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAoPKAQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAIYJtQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAo0JfQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAI9JJQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgApYI7QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAJfIlQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAp5IWQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAKAH+QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAqYHvQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAKdHWQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAq1HGQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAK4GsQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgArPGbQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgALRGAQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgArnFuQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgALnFTQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAr7FAQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAL5ElQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsOEPQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMJD2QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsdDfQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMWDGQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAspCtQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMgCWQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsxB8QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMnBlQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAs3BKQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMrAzQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAs5AYQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMsABQgDgCAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDACQgDADgEAAQgEAAgDgDgAs4gZQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMrgwQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAs1hMQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMmhhQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsuh+QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMeiTQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAslivQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMTjEQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsYjgQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMFjzQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsJkPQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAL0khQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAr1lAQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgALhlQQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgArglsQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgALLl8QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgArImYQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAKymnQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAqunDQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAKXnRQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAqQnrQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAJ5n5QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgApwoSQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAJYoeQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgApOo2QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAI8o7QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAorpYQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAIYpdQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAoEp5QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAHyp9QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAndqXQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAHKqbQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAmzqzQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAGgq2QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAmHrMQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAF1rPQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAlbriQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAFJrkQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAkrr1QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAEar3QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAj+sFQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgADrsHQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAjPsTQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAC7sVQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAieseQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgACMseQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAhtslQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgABasmQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAg7sqQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAAosqQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAgKsrQgDgDAAgEQAAgEADgDQADgDAEAAQADAAADADQADADAAAEQAAAEgDADQgDADgDAAQgEAAgDgDg");
	this.shape_1.setTransform(0,1);

	var maskedShapeInstanceList = [this.shape_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("ApXL9IAAvJISvAAIAAPJg");
	mask_2.setTransform(-1.5,76.5);

	// Layer_4
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgQM6QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQACADAAAEQAAAEgCADQgDADgEAAQgEAAgDgDgAAhM5QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAhCM4QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgABTM2QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAh0MzQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgACGMuQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAinMrQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAC3MkQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAjYMfQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgADmMYQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAkIMRQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAEXMHQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAk2L/QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAFHLzQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAllLrQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAF0LeQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAmRLVQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAGgLFQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAm9K7QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAHKKqQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAnnKeQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAHxKNQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAoPKAQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAIYJtQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAo0JfQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAI9JJQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgApYI7QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAJfIlQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAp5IWQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAKAH+QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAqYHvQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAKdHWQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAq1HGQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAK4GsQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgArPGbQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgALRGAQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgArnFuQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgALnFTQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAr7FAQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAL5ElQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsOEPQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMJD2QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsdDfQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMWDGQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAspCtQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMgCWQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsxB8QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMnBlQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAs3BKQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMrAzQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAs5AYQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMsABQgDgCAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDACQgDADgEAAQgEAAgDgDgAs4gZQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMrgwQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAs1hMQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMmhhQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsuh+QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMeiTQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAslivQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMTjEQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsYjgQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAMFjzQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAsJkPQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAL0khQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAr1lAQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgALhlQQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgArglsQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgALLl8QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgArImYQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAKymnQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAqunDQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAKXnRQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAqQnrQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAJ5n5QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgApwoSQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAJYoeQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgApOo2QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAI8o7QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAorpYQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAIYpdQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAoEp5QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAHyp9QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAndqXQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAHKqbQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAmzqzQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAGgq2QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAmHrMQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAF1rPQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAlbriQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAFJrkQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAkrr1QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAEar3QgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAj+sFQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgADrsHQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAjPsTQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAC7sVQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAieseQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgACMseQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAhtslQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgABasmQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAg7sqQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAAosqQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgDgDgAgKsrQgDgDAAgEQAAgEADgDQADgDAEAAQADAAADADQADADAAAEQAAAEgDADQgDADgDAAQgEAAgDgDg");
	this.shape_2.setTransform(0,1);

	var maskedShapeInstanceList = [this.shape_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

	// Layer_1
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#DDEBC7").ss(3).p("AH9n8QhohoiGg2QiCg1iNAAQiMAAiCA1QiHA2hnBoQhoBng2CHQg1CCAACMQAACNA1CCQA2CGBoBoQBnBnCHA3QCCA1CMAAQCNAACCg1QCGg3BohnQBnhoA3iGQA1iCAAiNQAAiMg1iCQg3iHhnhng");

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#8EC549").s().p("AkOKbQiHg3hnhnQhohog2iGQg1iCAAiNQAAiMA1iCQA2iHBohnQBnhoCHg2QCCg1CMAAQCNAACCA1QCGA2BoBoQBnBnA3CHQA1CCAACMQAACNg1CCQg3CGhnBoQhoBniGA3QiCA1iNAAQiMAAiCg1g");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#C5DE9E").s().p("AlSNCQiohEiCiCQiBiBhEipQhCiiAAiwQAAivBCiiQBEipCBiBQCCiCCohEQCjhCCvAAQCwAACiBCQCpBECBCCQCCCBBECpQBCCiAACvQAACwhCCiQhECpiCCBQiBCCipBEQiiBCiwAAQivAAijhCg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-89.9,-90,180,180);


(lib.stars = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_5 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(5).call(this.frame_5).wait(92));

	// Layer_1
	this.instance = new lib.Path();
	this.instance.parent = this;
	this.instance.setTransform(-122.1,-0.9,2,2,0,0,0,3,2.9);
	this.instance.alpha = 0.75;

	this.instance_1 = new lib.Path_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(120.3,-0.9,2,2,0,0,0,3,2.9);
	this.instance_1.alpha = 0.75;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1},{t:this.instance}]},4).to({state:[]},2).wait(91));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-128,-6.7,11.7,11.7);


// stage content:
(lib.social_connector = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_167 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(167).call(this.frame_167).wait(1));

	// stars
	this.stars = new lib.stars();
	this.stars.name = "stars";
	this.stars.parent = this;
	this.stars.setTransform(278.4,370.3);
	this.stars.alpha = 0;
	this.stars._off = true;

	this.timeline.addTween(cjs.Tween.get(this.stars).wait(27).to({_off:false},0).to({alpha:1},6).wait(135));

	// r hand
	this.instance = new lib.horn("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(349.2,381.2,1,1,0,-31.8,148.2,-7,0.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(33).to({_off:false},0).to({skewX:0,skewY:180,x:359.1,y:416.3,alpha:1},12).wait(123));

	// heart
	this.instance_1 = new lib.heart("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(277.6,312.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.flags = new lib.heart();
	this.flags.name = "flags";
	this.flags.parent = this;
	this.flags.setTransform(277.6,302.1,2.6,2.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_1}]},38).to({state:[{t:this.flags}]},10).wait(120));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(38).to({_off:false},0).to({_off:true,scaleX:2.6,scaleY:2.6,y:302.1,alpha:1,mode:"independent"},10).wait(120));

	// l hand
	this.instance_2 = new lib.horn("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(209.2,381.4,1,1,30.7,0,0,-7,0.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(33).to({_off:false},0).to({rotation:0,x:199.2,y:416.3,alpha:1},12).wait(123));

	// Layer_12 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_48 = new cjs.Graphics().p("AFPTTUgdggLcAtWgF1QOoGaDQmaIAARrQxvB5ogAAQpXAAB4iTg");
	var mask_graphics_49 = new cjs.Graphics().p("AEgTVUgdggLcAtWgF1QOoGaDQmaIAARrQxvB5ogAAQpXAAB4iTg");
	var mask_graphics_50 = new cjs.Graphics().p("ADwTXUgdfgLcAtVgF1QOoGaDQmaIAARrQxvB5ofAAQpXAAB3iTg");
	var mask_graphics_51 = new cjs.Graphics().p("ADBTZUgdfgLcAtVgF1QOoGaDQmaIAARrQxvB5ofAAQpXAAB3iTg");
	var mask_graphics_52 = new cjs.Graphics().p("ACSTbUgdggLbAtWgF2QOoGaDQmaIAARrQxvB5ogAAQpXAAB4iTg");
	var mask_graphics_53 = new cjs.Graphics().p("ABjTdUgdggLbAtWgF2QOoGaDQmaIAARrQxvB5ogAAQpWAAB3iTg");
	var mask_graphics_54 = new cjs.Graphics().p("AA0TfUgdggLbAtWgF2QOoGaDQmaIAARrQxvB5ogAAQpWAAB3iTg");
	var mask_graphics_55 = new cjs.Graphics().p("AAFThUgdggLbAtWgF2QOoGaDQmaIAARrQxvB5ogAAQpWAAB3iTg");
	var mask_graphics_56 = new cjs.Graphics().p("AgqTjUgdggLbAtVgF2QOoGaDQmaIAARrQxvB5ofAAQpWAAB3iTg");
	var mask_graphics_57 = new cjs.Graphics().p("AhZTmUgdggLcAtVgF1QOoGZDQmZIAARrQxvB4ofAAQpWAAB3iSg");
	var mask_graphics_58 = new cjs.Graphics().p("AiIToUgdhgLcAtWgF1QOoGZDQmZIAARrQxvB5ofAAQpXAAB4iTg");
	var mask_graphics_59 = new cjs.Graphics().p("Ai3TqUgdhgLcAtWgF1QOoGZDQmZIAARrQxvB5ogAAQpWAAB4iTg");
	var mask_graphics_60 = new cjs.Graphics().p("AjmTsUgdhgLcAtWgF1QOoGZDQmZIAARrQxvB5ogAAQpWAAB4iTg");
	var mask_graphics_61 = new cjs.Graphics().p("AkVTuUgdhgLcAtWgF1QOoGZDQmZIAARrQxvB5ogAAQpWAAB4iTg");
	var mask_graphics_62 = new cjs.Graphics().p("AlFTwUgdggLcAtVgF1QOoGZDQmZIAARrQxvB5ofAAQpWAAB3iTg");
	var mask_graphics_63 = new cjs.Graphics().p("Al0TyUgdggLcAtVgF1QOoGZDQmZIAARrQxvB5ofAAQpWAAB3iTg");
	var mask_graphics_64 = new cjs.Graphics().p("AmjT0UgdhgLcAtWgF1QOoGZDQmZIAARrQxvB5ogAAQpWAAB4iTg");
	var mask_graphics_65 = new cjs.Graphics().p("AnST2UgdhgLcAtWgF1QOoGZDQmZIAARrQxvB5ogAAQpWAAB4iTg");
	var mask_graphics_66 = new cjs.Graphics().p("AoBT4UgdhgLcAtWgF1QOoGaDQmaIAARrQxvB5ofAAQpXAAB4iTg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(48).to({graphics:mask_graphics_48,x:249.3,y:138.2}).wait(1).to({graphics:mask_graphics_49,x:244.6,y:138.4}).wait(1).to({graphics:mask_graphics_50,x:239.8,y:138.6}).wait(1).to({graphics:mask_graphics_51,x:235.1,y:138.8}).wait(1).to({graphics:mask_graphics_52,x:230.4,y:139}).wait(1).to({graphics:mask_graphics_53,x:225.7,y:139.2}).wait(1).to({graphics:mask_graphics_54,x:221,y:139.4}).wait(1).to({graphics:mask_graphics_55,x:216.3,y:139.6}).wait(1).to({graphics:mask_graphics_56,x:211.5,y:139.8}).wait(1).to({graphics:mask_graphics_57,x:206.8,y:140}).wait(1).to({graphics:mask_graphics_58,x:202.1,y:140.3}).wait(1).to({graphics:mask_graphics_59,x:197.4,y:140.5}).wait(1).to({graphics:mask_graphics_60,x:192.7,y:140.7}).wait(1).to({graphics:mask_graphics_61,x:188,y:140.9}).wait(1).to({graphics:mask_graphics_62,x:183.2,y:141.1}).wait(1).to({graphics:mask_graphics_63,x:178.5,y:141.3}).wait(1).to({graphics:mask_graphics_64,x:173.8,y:141.5}).wait(1).to({graphics:mask_graphics_65,x:169.1,y:141.7}).wait(1).to({graphics:mask_graphics_66,x:164.4,y:141.9}).wait(102));

	// l branch
	this.instance_3 = new lib.lbranch("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(185.8,199.9,2.6,2.6);
	this.instance_3._off = true;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(48).to({_off:false},0).wait(120));

	// Layer_13 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_48 = new cjs.Graphics().p("AyMTtIAAxrQDQGaOomaUAtWAF1gdhALcQB4CTpXAAQofAAxvh5g");
	var mask_1_graphics_49 = new cjs.Graphics().p("AxdTvIAAxrQDQGaOnmaUAtXAF1gdhALcQB4CTpXAAQogAAxuh5g");
	var mask_1_graphics_50 = new cjs.Graphics().p("AwuTxIAAxrQDQGaOnmaUAtXAF2gdhALbQB4CTpXAAQogAAxuh5g");
	var mask_1_graphics_51 = new cjs.Graphics().p("Av/T0IAAxrQDQGZOnmZUAtXAF1gdhALcQB4CTpXAAQogAAxuh5g");
	var mask_1_graphics_52 = new cjs.Graphics().p("AvQT2IAAxrQDQGZOnmZUAtXAF1gdhALcQB4CTpXAAQogAAxuh5g");
	var mask_1_graphics_53 = new cjs.Graphics().p("AugT4IAAxrQDQGaOnmaUAtWAF1gdgALcQB3CTpXAAQofAAxuh5g");
	var mask_1_graphics_54 = new cjs.Graphics().p("AtxT6IAAxrQDQGaOnmaUAtWAF1gdgALcQB3CTpXAAQofAAxuh5g");
	var mask_1_graphics_55 = new cjs.Graphics().p("AtCT8IAAxrQDQGaOnmaUAtXAF2gdhALbQB3CTpXAAQofAAxuh5g");
	var mask_1_graphics_56 = new cjs.Graphics().p("AsTT/IAAxrQDQGZOnmZUAtXAF1gdhALcQB4CTpYAAQofAAxuh5g");
	var mask_1_graphics_57 = new cjs.Graphics().p("ArkUBIAAxrQDQGZOnmZUAtXAF1gdhALcQB4CTpXAAQogAAxuh5g");
	var mask_1_graphics_58 = new cjs.Graphics().p("Aq1UDIAAxrQDQGZOnmZUAtXAF1gdhALcQB4CTpXAAQogAAxuh5g");
	var mask_1_graphics_59 = new cjs.Graphics().p("AqGUFIAAxrQDQGaOnmaUAtXAF1gdhALcQB4CTpXAAQogAAxuh5g");
	var mask_1_graphics_60 = new cjs.Graphics().p("ApXUHIAAxrQDQGaOnmaUAtXAF2gdhALbQB4CTpXAAQogAAxuh5g");
	var mask_1_graphics_61 = new cjs.Graphics().p("AooUKIAAxrQDQGZOnmZUAtXAF1gdhALcQB4CSpXAAQogAAxuh4g");
	var mask_1_graphics_62 = new cjs.Graphics().p("An4UMIAAxrQDQGZOnmZUAtWAF1gdgALcQB3CTpXAAQofAAxuh5g");
	var mask_1_graphics_63 = new cjs.Graphics().p("AnJUOIAAxrQDQGZOnmZUAtWAF1gdgALcQB3CTpXAAQofAAxuh5g");
	var mask_1_graphics_64 = new cjs.Graphics().p("AmaUQIAAxrQDQGaOnmaUAtXAF1gdhALcQB3CTpXAAQofAAxuh5g");
	var mask_1_graphics_65 = new cjs.Graphics().p("AlrUSIAAxrQDQGaOnmaUAtXAF2gdhALbQB4CTpYAAQofAAxuh5g");
	var mask_1_graphics_66 = new cjs.Graphics().p("Ak8UVIAAxrQDQGZOnmZUAtXAF1gdhALcQB4CSpXAAQogAAxuh4g");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(48).to({graphics:mask_1_graphics_48,x:173.8,y:138.2}).wait(1).to({graphics:mask_1_graphics_49,x:178.5,y:138.4}).wait(1).to({graphics:mask_1_graphics_50,x:183.2,y:138.6}).wait(1).to({graphics:mask_1_graphics_51,x:187.9,y:138.9}).wait(1).to({graphics:mask_1_graphics_52,x:192.6,y:139.1}).wait(1).to({graphics:mask_1_graphics_53,x:197.3,y:139.3}).wait(1).to({graphics:mask_1_graphics_54,x:202,y:139.5}).wait(1).to({graphics:mask_1_graphics_55,x:206.7,y:139.7}).wait(1).to({graphics:mask_1_graphics_56,x:211.4,y:140}).wait(1).to({graphics:mask_1_graphics_57,x:216.2,y:140.2}).wait(1).to({graphics:mask_1_graphics_58,x:220.9,y:140.4}).wait(1).to({graphics:mask_1_graphics_59,x:225.6,y:140.6}).wait(1).to({graphics:mask_1_graphics_60,x:230.3,y:140.8}).wait(1).to({graphics:mask_1_graphics_61,x:235,y:141}).wait(1).to({graphics:mask_1_graphics_62,x:239.7,y:141.3}).wait(1).to({graphics:mask_1_graphics_63,x:244.4,y:141.5}).wait(1).to({graphics:mask_1_graphics_64,x:249.1,y:141.7}).wait(1).to({graphics:mask_1_graphics_65,x:253.8,y:141.9}).wait(1).to({graphics:mask_1_graphics_66,x:258.6,y:142.1}).wait(102));

	// r branch
	this.instance_4 = new lib.lbranch("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(368.8,199.9,2.6,2.6,0,0,180);
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(48).to({_off:false},0).wait(120));

	// title
	this.instance_5 = new lib.title("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(277.8,151.1,2.6,2.6);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(65).to({_off:false},0).to({alpha:1},15).wait(88));

	// keywords
	this.instance_6 = new lib.keywords("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(276.4,232.5,2.6,2.6);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(29).to({_off:false},0).to({alpha:1},7).wait(132));

	// Art
	this.instance_7 = new lib.bg("synched",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(276.4,274.9,2.86,2.86,45);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({scaleX:2.6,scaleY:2.6,rotation:0,x:277.6,y:271.1,alpha:1,mode:"independent"},29).wait(139));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(294,292.5,514.8,514.8);
// library properties:
lib.properties = {
	id: '868A226D6E334E0689910F4725F92AB8',
	width: 550,
	height: 550,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['868A226D6E334E0689910F4725F92AB8'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;